name: GitHub Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "6.0"
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Archive build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifact
                  path: DemoTest/**/bin/Release/net6.0-windows/

    test:
        runs-on: windows-latest
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: build-artifact
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "6.0"
            - name: Test
              run: dotnet test --no-restore --verbosity normal --logger "trx;logfilename=testResults.trx" bin/Release/net6.0-windows/DemoTest.dll
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: test report
                  path: TestResults/testResults.trx
                  max-annotations: "0"
                  reporter: dotnet-trx
                  fail-on-error: "false"
