name: GitHub Actions

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "6.0"
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Archive build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifact
                  path: SeleniumFramework/**/bin/Release/net6.0-windows/

    test:
        runs-on: windows-latest
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v3
              with:
                  name: build-artifact
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "6.0"
            - name: Test
              run: dotnet test --no-restore --verbosity normal --logger "trx;logfilename=testResults.trx" bin/Release/net6.0-windows/SeleniumFramework.dll
            - name: Multi line step
              if: success() || failure()
              run: |
                  pwd
                  ls
            - name: Upload Test Report
              uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                  name: test-results
                  path: TestResults/testResults.trx
